-- Create the 'pets' table
create table pets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  breed text,
  age text,
  photo_url text,
  cuteness_level integer default 100,
  badges text[], -- Array of strings for badges like ['Friendly', 'Napper']
  status text default 'Active' -- 'Active', 'Checked In', etc.
);

-- Insert some sample data into 'pets'
insert into pets (name, breed, age, photo_url, cuteness_level, badges, status)
values
  ('Luna', 'Golden Retriever', '2 yrs', 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=150&q=80', 98, ARRAY['🎾 Ball Lover', '🌊 Swimmer', '🤝 Friendly'], 'Active'),
  ('Thor', 'French Bulldog', '4 yrs', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=150&q=80', 85, ARRAY['😴 Napper', '💨 Snorer', '🥔 Couch Potato'], 'Checked In'),
  ('Mochi', 'Shiba Inu', '1 yr', 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=150&q=80', 92, ARRAY['🦊 Fox-like', '👑 Diva', '🐕 Independent'], 'Active');

-- Create the 'bookings' table for Hotel/Daycare
create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pet_id bigint references pets(id),
  pet_name text, -- Storing name for easier display, or could join tables
  service_type text, -- 'Hotel' or 'Daycare'
  task_description text,
  status text default 'checkIn' -- 'checkIn', 'playtime', 'napTime', 'grooming', 'ready'
);

-- Insert some sample data into 'bookings'
insert into bookings (pet_name, service_type, task_description, status)
values
  ('Max', 'Daycare', 'Drop-off at 2PM', 'checkIn'),
  ('Bella', 'Hotel', 'Verify vaccination', 'checkIn'),
  ('Charlie', 'Daycare', 'Group A - Ball Fetch', 'playtime'),
  ('Lucy', 'Hotel', 'Quiet room', 'napTime'),
  ('Cooper', 'Daycare', 'Mom arriving at 5PM', 'ready');
