-- Create health_records table
create table if not exists public.health_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pet_id bigint references public.pets(id) on delete cascade,
  type text not null check (type in ('vaccine', 'checkup', 'medication', 'surgery')),
  title text not null,
  date date not null,
  next_date date,
  notes text
);

-- Enable RLS
alter table public.health_records enable row level security;

-- Create policy for authenticated users
create policy "Allow all for authenticated users"
  on public.health_records
  for all
  using (auth.role() = 'authenticated');
